config/routes.rb
Rails.application.routes.draw do

  resources :monsters
  resources :monster_teams

  namespace :api do
    namespace :v1 do
      resources :monsters
      resources :monster_teams
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'home#index'

end

app/models/monster.rb
class Monster < ActiveRecord::Base

  SUB_CLASSES = %w(fire water earth electric wind)

  belongs_to :user
  belongs_to :monster_team

  before_save :define_weakness

  validates :name, :power, :sub_class, :user_id, presence: true
  validates :sub_class, inclusion: { in: SUB_CLASSES }
  validate :validate_monsters_number, on: :create

  private

  def validate_monsters_number
    if user && user.monsters.count >= 20
      errors.add(:base, 'Monsters\' number is exceeded. ' \
                        'User should not have more than 20 monsters')
    end
  end

  def define_weakness
    sub_class_index = SUB_CLASSES.index(sub_class)
    self.weakness = find_weakness(sub_class_index)
  end

  def find_weakness(sub_class_index)
    if sub_class_index == (SUB_CLASSES.length - 1)
      SUB_CLASSES.first
    else
      SUB_CLASSES[sub_class_index + 1]
    end
  end
end

app/controllers/api/v1/monsters_controller.rb
module Api
  module V1
    class MonstersController < ApiController
      def index
        user = User.find_by(email: params[:user_email])
        render json: user.try(:monsters), each_serializer: MonsterSerializer
      end

      def show
        monster = Monster.find_by(id: params[:id])
        render json: monster, serializer: MonsterSerializer
      end

      def create
        monster = Monster.new(monster_params)
        if monster.save
          render status: 201, json: monster, serializer: MonsterSerializer
        else
          render status: 422, json: { monster: { errors: monster.errors } }
        end
      end

      def update
        monster = Monster.find_by(id: params[:id])
        if monster.update(monster_params)
          render status: 200, json: monster, serializer: MonsterSerializer
        else
          render status: 422, json: { monster: { errors: monster.errors } }
        end
      end

      def destroy
        monster = Monster.find_by(id: params[:id])
        if monster.destroy
          render status: 200, json: {}
        else
          render status: 422, json: { monster: {
                                          errors: 'Monster can\'t be deleted' }}
        end
      end

      private

      def monster_params
        params.require(:monster).permit(:name, :power, :sub_class, :user_id)
      end
    end
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]

  def index
    @q = current_user.monsters.ransack(params[:q])
    @monsters = @q.result
  end

  def show
  end

  def new
    @monster = current_user.monsters.new
  end

  def edit
  end

  def create
    @monster = current_user.monsters.new(monster_params)

    if @monster.save
      redirect_to @monster, notice: 'Monster was successfully created.'
    else
      render :new
    end
  end

  def update
    if @monster.update(monster_params)
      redirect_to @monster, notice: 'Monster was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @monster.destroy
    redirect_to monsters_url, notice: 'Monster was successfully destroyed.'
  end

  private
    def set_monster
      @monster = current_user.monsters.find(params[:id])
    end

    def monster_params
      params.require(:monster).permit(:name, :power, :sub_class)
    end
end

app/views/monsters/_form.html.erb
<%= form_for(@monster) do |f| %>
  <% if @monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% @monster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :power %><br>
    <%= f.text_field :power %>
  </div>
  <div class="field">
    <%= f.label :sub_class, 'Type' %><br>
    <%= f.select :sub_class, Monster::SUB_CLASSES %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monsters/edit.html.erb
<h1>Editing Monster</h1>

<%= render 'form' %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

app/views/monsters/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Monsters</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= sort_link @q, :name %></th>
      <th><%= sort_link @q, :power %></th>
      <th><%= sort_link @q, :sub_class, 'Type' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monsters.each do |monster| %>
      <tr>
        <td><%= monster.name %></td>
        <td><%= monster.power %></td>
        <td><%= monster.sub_class %></td>
        <td><%= link_to 'Show', monster %></td>
        <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
        <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monster', new_monster_path %>

app/views/monsters/new.html.erb
<h1>New Monster</h1>

<%= render 'form' %>

<%= link_to 'Back', monsters_path %>

app/views/monsters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @monster.name %>
</p>

<p>
  <strong>Power:</strong>
  <%= @monster.power %>
</p>

<p>
  <strong>Type:</strong>
  <%= @monster.sub_class %>
</p>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Back', monsters_path %>