config/routes.rb
Rails.application.routes.draw do

  resources :monsters
  resources :monster_teams

  namespace :api do
    namespace :v1 do
      resources :monsters
      resources :monster_teams
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'home#index'

end

app/models/monster_team.rb
class MonsterTeam < ActiveRecord::Base

  belongs_to  :user
  has_many    :monsters

  validates :name, presence: true
  validate :validate_team_size
  validate :user_team_limit

  private

  def validate_team_size
    errors.add(:size, 'should be equal to 3 monsters') if monsters.size != 3
  end

  def user_team_limit
    if user && user.monster_teams.count >= 3
      errors.add(:base, 'User is limited to 3 teams')
    end
  end
end

app/controllers/api/v1/monster_teams_controller.rb
module Api
  module V1
    class MonsterTeamsController < ApiController

      def index
        user = User.find_by(email: params[:user_email])
        render json: user.monster_teams.includes(:monsters),
               each_serializer: MonsterTeamSerializer
      end

      def show
        team = MonsterTeam.includes(:monsters).find_by(id: params[:id])
        render json: team, serializer: MonsterTeamSerializer
      end

      def create
        team = MonsterTeam.new(monster_team_params)

        if team.save
          render status: 201, json: team, serializer: MonsterTeamSerializer
        else
          render status: 422, json: { monster_team: { errors: team.errors } }
        end
      end

      def update
        team = MonsterTeam.find_by(id: params[:id])

        if team.update(monster_team_params)
          render status: 200, json: team, serializer: MonsterTeamSerializer
        else
          render status: 422, json: { monster_team: { errors: team.errors } }
        end
      end

      def destroy
        team = MonsterTeam.find_by(id: params[:id])

        if team.destroy
          render status: 200, json: {}
        else
          render status: 422, json: { monster_team: {
                                errors: 'Monster Team can\'t be deleted' }}
        end
      end

      private

      def monster_team_params
        params.require(:monster_team).permit(:name, :user_id, monster_ids: [])
      end
    end
  end
end

app/controllers/monster_teams_controller.rb
class MonsterTeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  def index
    @teams = current_user.monster_teams
  end

  def show
  end

  def new
    @team = current_user.monster_teams.new
  end

  def create
    @team = current_user.monster_teams.new(monster_team_params)

    if @team.save
      redirect_to @team, notice: 'Monster Team was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @team.update(monster_team_params)
      redirect_to @team, notice: 'Monster Team was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @team.destroy
    redirect_to monster_teams_url, notice: 'Monster Team was successfully destroyed.'
  end

  private

  def set_team
    @team = current_user.monster_teams.find(params[:id])
  end

  def monster_team_params
    params.require(:monster_team).permit(:name, monster_ids: [])
  end
end

app/views/monster_teams/_form.html.erb
<%= form_for(@team) do |f| %>
  <% if @team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team.errors.count, "error") %> prohibited this monster team from being saved:</h2>

      <ul>
        <% @team.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.collection_check_boxes(:monster_ids, current_user.monsters, :id, :name) do |builder| %>
      <%= builder.check_box %>
      <%= builder.label %>
      <br/>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monster_teams/edit.html.erb
<h1>Editing Monster Team</h1>

<%= render 'form' %>

<%= link_to 'Show', @team %> |
<%= link_to 'Back', monster_teams_path %>

app/views/monster_teams/index.html.erb
<h1 class="text-center">Monster Teams</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @teams.each do |team| %>
    <tr>
      <td><%= team.name %></td>
      <td><%= link_to 'Show', team %></td>
      <td><%= link_to 'Edit', edit_monster_team_path(team) %></td>
      <td><%= link_to 'Destroy', team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monster Team', new_monster_team_path %>

app/views/monster_teams/new.html.erb
<h1>New Monster Team</h1>

<%= render 'form' %>

<%= link_to 'Back', monster_teams_path %>

app/views/monster_teams/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @team.name %>
</p>

<p>
  <strong>Monsters:</strong>
  <ul>
    <% @team.monsters.each do |monster| %>
      <li><%= monster.name %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_monster_team_path(@team) %> |
<%= link_to 'Back', monster_teams_path %>